# Default values for leaderboard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
hostname: example.com
storageClass: local-path
game:
  competitionDuration: 200
  queueWaitingTimeout: 30
  competitionSize: 10
  minCompetitionSize: 2
