swagger: "2.0"
info:
  version: "1.0.0"
  title: Leaderboard API
  description: API for managing leaderboard entries and scores.

host: "api.example.com"
basePath: "/"
schemes:
  - "http"

paths:
  /leaderboard/join:
    post:
      operationId: join
      summary: "Join leaderboard"
      description: "Endpoint to join a leaderboard using player_id"
      parameters:
        - name: "player_id"
          in: "query"
          description: "ID of the player"
          required: true
          type: "string"
      responses:
        202:
          description: "Accepted"
        409:
          description: "Conflict"

  /leaderboard/player/{player_id}:
    get:
      operationId: getPlayerLeaderboard
      summary: "Get player's leaderboard"
      description: "Retrieve leaderboard data for a specific player"
      parameters:
        - name: "player_id"
          in: "path"
          description: "ID of the player"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/LeaderboardResponse"

  /leaderboard/{leaderboard_id}:
    get:
      summary: "Get leaderboard by ID"
      operationId: getLeaderboard
      description: "Retrieve leaderboard data by leaderboard ID"
      parameters:
        - name: "leaderboard_id"
          in: "path"
          description: "ID of the leaderboard"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/LeaderboardResponse"
        404:
          description: "Leaderboard not found"

  /leaderboard/score:
    post:
      summary: "Submit player score"
      operationId: addScores
      description: "Submit or update a player's score"
      parameters:
        - in: "body"
          name: "score"
          description: "Player score submission"
          required: true
          schema:
            $ref: "#/definitions/ScoreSubmission"
      responses:
        200:
          description: "Score updated"
        409:
          description: "Conflict, score not accepted"

definitions:
  LeaderboardResponse:
    type: "object"
    properties:
      leaderboard_id:
        type: "string"
        description: "ID of the leaderboard"
      ends_at:
        type: "string"
        format: "date-time"
        description: "Timestamp of leaderboard end"
      leaderboard:
        type: "array"
        items:
          $ref: "#/definitions/PlayerScore"

  PlayerScore:
    type: "object"
    properties:
      player_id:
        type: "string"
        description: "ID of the player"
      score:
        type: "integer"
        description: "Player's score"
    required:
      - player_id
      - score

  ScoreSubmission:
    type: "object"
    properties:
      player_id:
        type: "string"
        description: "ID of the player"
      score:
        type: "integer"
        description: "Score to be submitted"
    required:
      - player_id
      - score
