# name: CI

# on:
#   push:
#     branches:
#       - "**"
#   pull_request:
#     branches:
#       - "**"

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     container:
#       image: golang:1.22.1
#     services:
#       docker:
#         image: docker:20.10.7
#         options: --privileged
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # - name: Run tests
#       #   run: |
#       #     cd ./src
#       #     go mod download
#       #     go test -v .

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: ./src
#           push: true
#           tags: leaderboard:latest

name: ci
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aqaliarept/leaderboard:latest
